DROP DATABASE TARTEDELAVIE;
CREATE DATABASE  TARTEDELAVIE;
USE TARTEDELAVIE;


CREATE TABLE PERSONA(
	ID_PERSONA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDOS VARCHAR(50) NOT NULL,
	SEXO BOOL
);
CREATE TABLE DIRECCIONES(
	ID_DIRECCION INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	DIRECCION TEXT
);
CREATE TABLE REL_DIR_PERSONA(
	ID_REL INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	ID_PERSONA INT NOT NULL,
	ID_DIRECCION INT NOT NULL,
	FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(ID_PERSONA),
	FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCIONES(ID_DIRECCION)
);
CREATE TABLE USUARIO(
	ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	USUARIO TEXT NOT NULL,
	CONTRASENA TEXT NOT NULL,
	ID_PERSONA INT NOT NULL,
	TIPO VARCHAR(30) NOT NULL,
	FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(ID_PERSONA)
);

CREATE TABLE TARJETA(
	ID_TARJETA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NUMERO TEXT NOT NULL,
	CVV INT NOT NULL,
	BANCO TEXT NOT NULL,
	FONDOS INT NOT NULL
);
CREATE TABLE REL_TARJETA_USUARIO(
	ID_REL INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	ID_TARJETA INT NOT NULL,
	ID_USUARIO INT NOT NULL,
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY (ID_TARJETA) REFERENCES TARJETA(ID_TARJETA)
);
CREATE TABLE INVENTARIO(
	ID_INVENTARIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	PRODUCTO VARCHAR(50) NOT NULL,
	CANTIDAD INT NOT NULL,
	DESCRIPCION TEXT
);

CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NOMBRE VARCHAR(40) NOT NULL,
	DESCRIPCION TEXT NOT NULL,
	PRECIO FLOAT NOT NULL,
	IMG TEXT
);

CREATE TABLE REL_INVENTARIO_PRODUCTO(
	ID_RELACION INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	ID_INVENTARIO INT,
	ID_PRODUCTO INT,
	CANTIDAD INT,
	FOREIGN KEY (ID_INVENTARIO) REFERENCES INVENTARIO(ID_INVENTARIO),
	FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE TIPO_OFERTAS(
	ID_TO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	TIPO TEXT NOT NULL,
	VALOR FLOAT NOT NULL
);


CREATE TABLE REL_OFERTAS_PRODUCTO(
	ID_REL INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	ID_OFERTA INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	FOREIGN KEY (ID_OFERTA) REFERENCES TIPO_OFERTAS(ID_TO),
	FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE PEDIDOS(
	ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ESTADO TEXT,
	CANTIDAD INT,
	FECHA_ENTREGA DATE,
	FECHA_PEDIDO DATE,
	FOREIGN KEY (ID_CLIENTE) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE PENDIENTES(
	ID_PENDIENTES INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	ID_PEDIDO INT NOT NULL,
	FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);

CREATE TABLE REL_PEDIDOS_INVENTARIO(
	ID_REL INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	ID_PEDIDO INT NOT NULL,
	ID_MATERIALES INT NOT NULL,
	FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
	FOREIGN KEY (ID_MATERIALES) REFERENCES PRODUCTO(ID_PRODUCTO) 
);