DROP PROCEDURE ALTA_CLIENTE;
DELIMITER //

CREATE PROCEDURE ALTA_CLIENTE(FNAME VARCHAR(50),LNAME VARCHAR(50),SEX BOOL,
USERS TEXT,PASS TEXT)
BEGIN
	DECLARE EXISTE INT;
	SET EXISTE = (SELECT COUNT(USUARIO.USUARIO) FROM USUARIO WHERE USERS = USUARIO);
	IF (EXISTE > 0) THEN
		SELECT "USUARIO YA EXISTENTE" AS MENSAJE;
	ELSE 
		INSERT INTO PERSONA(NOMBRE,APELLIDOS,SEXO) VALUES(FNAME,LNAME,SEX);
		INSERT INTO USUARIO (USUARIO,CONTRASENA,ID_PERSONA,TIPO) VALUES (USERS,MD5(PASS),LAST_INSERT_ID(),"CLIENTE");
		SELECT "USUARIO REGISTRADO" AS MENSAJE;
	END IF;
	
END
//
DELIMITER ;

